# Generated by Django 4.1.7 on 2023-02-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
