# Generated by Django 4.1.7 on 2023-02-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artworks',
            new_name='Artwork',
        ),
    ]
