# Generated by Django 4.1.7 on 2023-02-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_rename_artworks_artwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['category', 'subject']},
        ),
    ]
